services:
  mysql:
    image: mysql:8.0 # Using a stable MySQL 8.0 image
    hostname: mysql
    ports:
      - '3306:3306' # Expose MySQL port to your host
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password 
      MYSQL_DATABASE: your_app_test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: your_strong_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest # Using the latest phpMyAdmin image
    hostname: phpmyadmin
    ports:
      - '8080:80' # Expose phpMyAdmin on port 8080 (you can change this)
    environment:
      PMA_HOST: mysql # This tells phpMyAdmin to connect to the 'mysql' service
      MYSQL_ROOT_PASSWORD: your_root_password # Use the same root password as your MySQL service
    depends_on:
      - mysql # Ensure MySQL is running before starting phpMyAdmin

# No named volumes defined, as neither Redis nor MySQL data needs to persist.
